# Generated by Django 5.1.4 on 2025-01-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0004_delete_case_delete_cpu_delete_cpucooler_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("case_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("psu", models.CharField(blank=True, max_length=255, null=True)),
                ("side_panel", models.CharField(max_length=50)),
                ("external_525_bays", models.IntegerField()),
                ("internal_35_bays", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Cpu",
            fields=[
                ("cpu_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("core_count", models.IntegerField()),
                ("core_clock", models.FloatField()),
                ("boost_clock", models.FloatField()),
                ("tdp", models.IntegerField()),
                ("graphics", models.CharField(blank=True, max_length=255, null=True)),
                ("smt", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="CpuCooler",
            fields=[
                ("cpu_cooler_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("rpm_min", models.IntegerField(blank=True, null=True)),
                ("rpm_max", models.IntegerField(blank=True, null=True)),
                ("noise_level_min", models.FloatField(blank=True, null=True)),
                ("noise_level_max", models.FloatField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InternalHardDrive",
            fields=[
                (
                    "internal_hard_drive_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("capacity", models.IntegerField()),
                ("price_per_gb", models.FloatField()),
                ("type", models.CharField(max_length=50)),
                ("cache", models.IntegerField(blank=True, null=True)),
                ("form_factor", models.CharField(max_length=50)),
                ("interface", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                ("memory_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("speed_min", models.IntegerField()),
                ("speed_max", models.IntegerField()),
                ("module_count", models.IntegerField()),
                ("module_size", models.IntegerField()),
                ("price_per_gb", models.FloatField()),
                ("color", models.CharField(max_length=50)),
                ("first_word_latency", models.FloatField()),
                ("cas_latency", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                ("motherboard_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("socket", models.CharField(max_length=50)),
                ("form_factor", models.CharField(max_length=50)),
                ("max_memory", models.IntegerField()),
                ("memory_slots", models.IntegerField()),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PowerSupply",
            fields=[
                (
                    "power_supply_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                ("efficiency", models.CharField(max_length=50)),
                ("wattage", models.IntegerField()),
                ("modular", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
