# Generated by Django 5.1.4 on 2025-01-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0005_case_cpu_cpucooler_internalharddrive_memory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="side_panel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
