# Generated by Django 5.1.4 on 2025-01-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0006_alter_case_side_panel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpu",
            name="boost_clock",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
