# Generated by Django 5.1.4 on 2025-01-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0007_alter_cpu_boost_clock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
