# Generated by Django 5.1.4 on 2025-01-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0008_alter_memory_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
