# Generated by Django 5.1.4 on 2025-01-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0009_alter_memory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="price_per_gb",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
