# Generated by Django 5.1.4 on 2025-01-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0010_alter_memory_price_per_gb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="speed_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="memory",
            name="speed_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
