# Generated by Django 5.1.4 on 2025-01-05 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0014_alter_powersupply_efficiency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSelections",
            fields=[
                ("saved_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_cases",
                        to="picker.case",
                    ),
                ),
                (
                    "cpu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_cpus",
                        to="picker.cpu",
                    ),
                ),
                (
                    "cpu_cooler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_cpu_coolers",
                        to="picker.cpucooler",
                    ),
                ),
                (
                    "internal_hard_drive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_hard_drives",
                        to="picker.internalharddrive",
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_memories",
                        to="picker.memory",
                    ),
                ),
                (
                    "motherboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_motherboards",
                        to="picker.motherboard",
                    ),
                ),
                (
                    "power_supply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_power_supplies",
                        to="picker.powersupply",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_selections",
                        to="picker.user",
                    ),
                ),
            ],
        ),
    ]
