# Generated by Django 5.1.4 on 2025-01-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0016_rename_user_userprofile_alter_savedselections_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedselections",
            name="case",
        ),
        migrations.RemoveField(
            model_name="savedselections",
            name="cpu",
        ),
        migrations.RemoveField(
            model_name="savedselections",
            name="cpu_cooler",
        ),
        migrations.RemoveField(
            model_name="savedselections",
            name="internal_hard_drive",
        ),
        migrations.RemoveField(
            model_name="savedselections",
            name="memory",
        ),
        migrations.RemoveField(
            model_name="savedselections",
            name="motherboard",
        ),
        migrations.RemoveField(
            model_name="savedselections",
            name="power_supply",
        ),
        migrations.AddField(
            model_name="savedselections",
            name="case_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedselections",
            name="cpu_cooler_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedselections",
            name="cpu_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedselections",
            name="internal_hard_drive_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedselections",
            name="memory_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedselections",
            name="motherboard_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedselections",
            name="power_supply_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
