# Generated by Django 5.1.4 on 2025-01-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0017_remove_savedselections_case_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="external_525_bays",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
