# Generated by Django 5.1.4 on 2025-01-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0018_alter_case_external_525_bays"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="internal_35_bays",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
