# Generated by Django 5.1.4 on 2025-01-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0020_alter_cpu_core_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpu",
            name="core_clock",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
