# Generated by Django 5.1.4 on 2025-01-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0022_alter_cpu_tdp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpu",
            name="smt",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="internalharddrive",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="max_memory",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="memory_slots",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="powersupply",
            name="wattage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
