# Generated by Django 5.1.4 on 2025-01-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0023_alter_cpu_smt_alter_internalharddrive_capacity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPU",
            fields=[
                ("gpu_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("chipset", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "memory",
                    models.PositiveIntegerField(
                        blank=True, help_text="Memory size in GB", null=True
                    ),
                ),
                (
                    "core_clock",
                    models.PositiveIntegerField(
                        blank=True, help_text="Core clock speed in MHz", null=True
                    ),
                ),
                (
                    "boost_clock",
                    models.PositiveIntegerField(
                        blank=True, help_text="Boost clock speed in MHz", null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "length",
                    models.PositiveIntegerField(
                        blank=True, help_text="Length in mm", null=True
                    ),
                ),
            ],
        ),
    ]
